# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Mon Feb 20 15:30:40 2023
#
import os
import subprocess
import sys
import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Jeux1(wx.Panel):
    def __init__(self, parent, *args, **kwds):
        # begin wxGlade: Jeux1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("./images/snake.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(bitmap_1, 0, wx.ALL, 200)

        grid_sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 3)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"SNAKE:\nLe jeu du snake est un ou on incarne un serpent qui doit manger le plus de pommes possibles  et a chaque fois qu'il mange une pomme, il grandit.\n\nLe but est de manger le plus de pommes possible sans se manger soit même ou toucher les murs.")
        label_1.SetMinSize((500, 93))
        label_1.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Ubuntu"))
        grid_sizer_1.Add(label_1, 0, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 161)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1.Add(sizer_2, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 10)

        self.button_1 = wx.Button(self, wx.ID_ANY, "Retour")
        sizer_2.Add(self.button_1, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 0)

        self.button_2 = wx.Button(self, wx.ID_ANY, "Jouer")
        sizer_2.Add(self.button_2, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.OnRetour, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.open_file, self.button_2)
        # end wxGlade
        self.leParent = parent

    def OnRetour(self, event):  # wxGlade: Jeux1.<event_handler>
        self.leParent.panelDetailJeux1.Hide()
        self.leParent.panelMaitre.Show()
        self.leParent.Layout()

# def une function pour start les jeux

   
    def open_file(self, event):  # wxGlade: Pong.<event_handler>
        if sys.platform == "win32":
            os.startfile("./snake/Snake.py")
        else:
            "python" if sys.platform == "darwin" else "xdg-open"
            subprocess.run([sys.executable, "snake/Snake.py"])

# end of class Jeux1
