# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Mon Feb 20 15:44:38 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PanneauMaitre(wx.Panel):
    def __init__(self, parent, *args, **kwds):
        # begin wxGlade: PanneauMaitre.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        conteneur = wx.WrapSizer(wx.HORIZONTAL)
        sizer_1.Add(conteneur, 0, wx.ALL | wx.EXPAND, 46)

        self.snake = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("./images/snake.png", wx.BITMAP_TYPE_ANY))
        self.snake.SetSize(self.snake.GetBestSize())
        conteneur.Add(self.snake, 0, wx.ALL, 8)

        self.spaceInvaders = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("./images/spaceInvaders.png", wx.BITMAP_TYPE_ANY))
        self.spaceInvaders.SetSize(self.spaceInvaders.GetBestSize())
        conteneur.Add(self.spaceInvaders, 0, wx.ALL, 8)

        self.comet_fall = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("./images/comet.png", wx.BITMAP_TYPE_ANY))
        self.comet_fall.SetSize(self.comet_fall.GetBestSize())
        conteneur.Add(self.comet_fall, 0, wx.ALL, 8)

        self.pong = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("./images/pong.png", wx.BITMAP_TYPE_ANY))
        self.pong.SetSize(self.pong.GetBestSize())
        conteneur.Add(self.pong, 0, wx.ALL, 8)

        self.rpg = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("./images/rpg.png", wx.BITMAP_TYPE_ANY))
        self.rpg.SetSize(self.rpg.GetBestSize())
        conteneur.Add(self.rpg, 0, wx.ALL, 8)

        self.tetris = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("./images/tetris.png", wx.BITMAP_TYPE_ANY))
        self.tetris.SetSize(self.tetris.GetBestSize())
        conteneur.Add(self.tetris, 0, wx.ALL, 8)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.OnBtnJeux1, self.snake)
        self.Bind(wx.EVT_BUTTON, self.OnBtnJeux2, self.spaceInvaders)
        self.Bind(wx.EVT_BUTTON, self.OnBtnJeux3, self.comet_fall)
        self.Bind(wx.EVT_BUTTON, self.OnBtnJeux4, self.pong)
        self.Bind(wx.EVT_BUTTON, self.OnBtnJeux5, self.rpg)
        self.Bind(wx.EVT_BUTTON, self.OnBtnJeux6, self.tetris)
        # end wxGlade
        self.leParent = parent # La fenetre parente pour pouvoir faire les show et hide

    def OnBtnJeux1(self, event):  # wxGlade: PanneauMaitre.<event_handler>
        self.leParent.panelDetailJeux1.Show()
        self.leParent.panelMaitre.Hide()
        self.leParent.Layout()
    def OnBtnJeux2(self, event):  # wxGlade: PanneauMaitre.<event_handler>
        self.leParent.panelDetailSpaceInvaders.Show()
        self.leParent.panelMaitre.Hide()
        self.leParent.Layout()

    def OnBtnJeux3(self, event):  # wxGlade: PanneauMaitre.<event_handler>
        self.leParent.panelDetailCometFall.Show()
        self.leParent.panelMaitre.Hide()
        self.leParent.Layout()

    def OnBtnJeux4(self, event):  # wxGlade: PanneauMaitre.<event_handler>
        self.leParent.panelDetailPong.Show()
        self.leParent.panelMaitre.Hide()
        self.leParent.Layout()

    def OnBtnJeux5(self, event):  # wxGlade: PanneauMaitre.<event_handler>
        self.leParent.panelDetailRpg.Show()
        self.leParent.panelMaitre.Hide()
        self.leParent.Layout()
    
    def OnBtnJeux6(self, event):  # wxGlade: PanneauMaitre.<event_handler>
        self.leParent.panelDetailTetris.Show()
        self.leParent.panelMaitre.Hide()
        self.leParent.Layout()
# end of class PanneauMaitre
